postgres:
  build: postgres
  restart: always
  ports:
     - 5432:5432

  labels:
    io.rancher.scheduler.affinity:host_label: changeme

  #named volume created only if it does not exist
  volumes:
    - postgis_data:/var/lib/postgresql/data
    - changeme:/ssl/server.crt:ro
    - changeme:/ssl/server.key:ro
    - changeme:/ssl/ca-bundle.crt:ro
    - changeme:/ssl/chain.crt:ro

  environment:
    #password used only when creating the database file cluster
    POSTGRES_PASSWORD: changeme
    POSTGRES_CONFIG_max_connections: 25
    POSTGRES_CONFIG_shared_buffers: 3GB
    POSTGRES_CONFIG_effective_cache_size: 4GB
    POSTGRES_CONFIG_work_mem: 128MB
    POSTGRES_CONFIG_maintenance_work_mem: 512MB
    POSTGRES_CONFIG_min_wal_size: 4GB
    POSTGRES_CONFIG_max_wal_size: 8GB
    POSTGRES_CONFIG_checkpoint_completion_target: 0.9
    POSTGRES_CONFIG_wal_buffers: 16MB
    POSTGRES_CONFIG_default_statistics_target: 500
    #enable the following only with 9.6
    #POSTGRES_CONFIG_max_parallel_workers_per_gather: 2

    SERVER_NAME: changeme

    PG_HBA: |-
       local   changeme         changeme         changeme          ident
       host    changeme         changeme         changeme          md5
       hostssl    changeme         changeme         changeme          md5

